### ISSUE TITLE
Invalid Byte at Offset error

### ISSUE THREAD

**Issue by Skeithh** [PaaaulZ/PhotoViewerOutOfMemoryNoMore#3]
Patcher doesn't seem to be working for me :( It tells me "invalid byte at offset, unsupported DLL version?"

Unsure what to do to fix this D:

**Comment by PaaaulZ** [comment]
Did you try with the other method? Also select the path to the included "SigScanner.exe"

**Comment by Skeithh** [comment]
Editing the image in notepad++ to alter the ICC_PROFILE line does make the image viewable again, as expected.

The sigscanner patch doesn't error with the invalid byte error but seems to do nothing to the file, as the out-of-memory issue persists.

**Comment by PaaaulZ** [comment]
Did you replace the patched dll in the Windows Photo Viewer folder? Also try patching both the 64bit version (in Program Files) and the 32bit in (Program files (x86)). Usually Windows uses the 32bit photo viewer even in 64bit environment

**Comment by Skeithh** [comment]
yep, DLL was replaced. I also went ahead and did the same to the 32bit one but issue still persists.

**Comment by PaaaulZ** [comment]
Could you upload both original dll files somewhere and send me the link? Also check which version of windows you are on by running "winver" and tell me
I can try and see what is the issue

**Comment by Skeithh** [comment]
https://drive.google.com/file/d/1wqp7PcTIfk_ElfFRv3tQE67k-_Mk-Qmc/view?usp=sharing
These should be the two. Labelled them with the folder they came from respectively.

I'm on windows 10,  version is 22H2 (OS Build 19045.2486)

**Comment by PaaaulZ** [comment]
Can you try with the new release I just posted? I added support for your dll version so you can avoid using SigScanner.exe, you can use the "Patch" button. If still does not work try the sigscan method and note that it should open a command prompt with logs, let me know what does it say if it fails.
If the command prompt does not open maybe the antivirus is blocking SigScanner.exe, Windows Defender is not liking it very well but since you sent me the dll you can avoid using it if you don't trust it

**Comment by Skeithh** [comment]
This fixed it! and indeed windows defender threw a fit about it, but malwarebytes reported it clean :) Thank you so much for being so swift in this and for making this patcher!
I'll be using anything else besides windows photo viewer when hell freezes over d:
